image: php:8.3-fpm

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
          - mysql
          - redis
        script:
          - apt-get update && apt-get install -y unzip libicu-dev libzip-dev git
          - docker-php-ext-install intl zip pdo_mysql
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-interaction --prefer-dist
          - php bin/console messenger:setup-transports # si nécessaire
          - ./vendor/bin/phpstan analyse src tests
          - ./vendor/bin/php-cs-fixer fix --dry-run --diff
          - ./vendor/bin/rector process --dry-run
          - php bin/phpunit
        caches:
          - composer

definitions:
  services:
    mysql:
      image: mariadb:10.11
      environment:
        MYSQL_DATABASE: symfony
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    redis:
      image: redis:7.2
